### ISSUE TITLE
Add RefreshTokenAsync() to DiscordRestClient

### ISSUE THREAD

**Issue by Auralytical** [discord-net/Discord.Net#152]

**Comment by RogueException** [comment]
Refresh tokens never expire, but access tokens expire every week (I think?) currently. We need an easy way to refresh them for private RPC.

**Comment by RogueException** [comment]
We could also add a new TokenType of Refresh, which will automatically refresh tokens.

**Comment by RogueException** [comment]
We should discuss how we want this first. TokenType.Refresh makes things complicated since it now needs a client secret and client id, in addition to the refresh token. We could pass these in through DiscordRestConfig?

If we ignore this, then simple RPC bots need to refresh tokens themselves... is that too complicated for the average bot?
